### ISSUE TITLE
hls-urls with token

### ISSUE THREAD

**Issue by Bond246** [kevinGodell/mp4frag#15]
Hello Kevin

i have a dashboard with multible sources to monitor. The player plugin is wonderful for that. Otherwise i had to do a lot of self works.

All urls i have are playing fine with one exception:
There is one URL that is build similare to this one:
https://out.example.com/edge/ABC323_AbABce/playlist.m3u8?token=<some 150 characters string with upper and lower case characters and with dots and dashes>

The mp4frag-player does not play this one. But there are also no error messages or similar hints that could help.
In hlsjs demo player, vlc and so on the url is playing fine.

**Comment by kevinGodell** [comment]
Can I assume that you are referring to [node-red-contrib-ui-mp4frag](https://github.com/kevinGodell/node-red-contrib-ui-mp4frag)? If yes, for a workaround, try adding another generic param to the end of your url such as `&format=.m3u8`.

**Comment by Bond246** [comment]
> 
> 
> Can I assume that you are referring to [node-red-contrib-ui-mp4frag](https://github.com/kevinGodell/node-red-contrib-ui-mp4frag)?

ah yes, of course

>for a workaround, try adding another generic param to the end of your url such as &format=.m3u8.

brilliant that works! 👍 
so from my point of view the project is ready für the official npm. 💯

**Comment by kevinGodell** [comment]
The reason that hack worked is because I check the payload string to end with ".m3u8" to know that it is the correct format to feed to hls.js player. You could shorten it to `&f=.m3u8`. The important thing is that it should be at the very end.
