### ISSUE TITLE
Reviewer/Co-owner for TypeScript support via DefinitelyTyped

### ISSUE THREAD

**Issue by kensand** [kevinGodell/mp4frag#30]
Hi mp4frag maintainers,

First of all, thank you for the fantastic library - I am using it in a new spare-time TypeScript project of mine (I'll let you know more about it in the future once I'm ready to publish it)

As mentioned, I am using your library in TypeScript, which requires [type declarations](https://www.typescriptlang.org/docs/handbook/2/type-declarations.html#dts-files) for proper typing, that you understandably don't have in a JavaScript project. I have written the declarations for mp4frag and submitted them to DefinitelyTyped [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61438) - I was wondering if any of you were interested in:
1. Reviewing the definitions - I am certainly not as familiar with the inner workings of your library as you are, and the definitions should be as accurate as possible.
2. Being a co-owner of the definitions - as you maintain the mp4frag JS package, it would certainly be appreciated if you were willing to also update the TS definitions too. It's also just good to have >1 owners for a public piece of code anyways. If not, no worries; I'll do my best to keep these definitions updated as well.

Thank you!

Ken Sanders

**Comment by kensand** [comment]
[The declarations for 0.6.0 have been merged and are available](https://www.npmjs.com/package/@types/mp4frag) for what it's worth, but the offer is still open :smile:

**Comment by kevinGodell** [comment]
Thanks for the info. I have not yet played with typescript, so I will trust that you have done it correctly. Keep me posted on your project. I am curious to what you will make.

**Comment by kensand** [comment]
Closing this out for the sake of completeness, look forward to any collaboration in the future :)

**Comment by kensand** [comment]
Just an update since you were curious :smile: 

I ended up migrating the project ([Rewynd](https://codeberg.org/rewynd-io/rewynd)) I am working on to Kotlin from TypeScript, and in order to do so I rewrote Mp4Frag in Kotlin Multiplatform and named it [Margarita](https://codeberg.org/kensand/margarita). It is available on [Maven Central](https://mvnrepository.com/artifact/net.kensand/margarita).

Please do let me know if you have any issues with the license or whatnot; I kept the MIT license and your copyright, so hopefully everything is kosher.
