### ISSUE TITLE
I get a lot of these: [error] "Error: ftyp not found."

### ISSUE THREAD

**Issue by WhiteLionATX** [kevinGodell/mp4frag#31]
I updated by using Node Red Palette Manager your nodes to current (nodeJs dependencies):
    "@kevingodell/node-red-ffmpeg": "0.1.1-beta.3",
    "@kevingodell/node-red-mp4frag": "0.1.1-beta.1",
    "@kevingodell/node-red-ui-mp4frag": "0.1.1-beta.1"

With this I messed something up because of renaming the node:
(You removed "-spawn" of "node-red-mp4frag" )

After that I had to change some settings to get cams work again:
I think mainly I switched "Auto Start", "Serve Io" and "Serve HTTP" to true.
 
Now I often get a lot of these errors, but sometimes it does work: 
"Error: ftyp not found."
<img width="443" alt="image" src="https://user-images.githubusercontent.com/36136622/209865934-6b1fc575-8c56-4452-a811-5a3de635d180.png">

btw. I am just wondering if you use other version numbers on git as the ones the dependencies show ?!

Greetings

**Comment by kevinGodell** [comment]
Hey there. When you say "You removed "-spawn" of "node-red-mp4frag" , hopefully you meant that about the formerly ffmpeg-spawn node and not mp4frag node.

My hunch is that this might be related to this issue in the node-red editor(https://discourse.nodered.org/t/is-a-flow-considered-to-be-dirty-modified-if-one-of-its-wires-is-cut/72732) that does not properly re-initialize  nodes that had a wire added or removed. Based on the partial screenshot of the debug 30 and 31, I would guess that the errors started right after adding them and then you deployed "modified nodes" and your debug window became very active. The bug causes all of the nodes in the flow to be re-initialized except for the node that had a wire added or removed on its output. Being that node-red-mp4frag was re-initialized but ffmpeg was not, mp4frag was now in a state where it is expecting to received the beginning chunk (ftyp) of the streamed mp4 from ffmpeg, but ffmpeg was already way past that chunk.

Also, the correct repo would have been https://github.com/kevinGodell/node-red-mp4frag, as this current repo (mp4frag) is just a dependency used by the node-red-mp4frag. I am sure that the naming be similar must have caused some confusion. 

If you are able, can you please open a thread on the node-red forum and tag me? It will be much easier for me to diagnose the problem and check out your flows, etc. I am sure we can make it work.

**Comment by WhiteLionATX** [comment]
Thanx for you fast and detailed reply. Your first guess may be the reason for this issue. At least I did not get these error again after restarting node red. If I get it again I will open a thread on the node-red forum.

**Comment by kevinGodell** [comment]
Yeah, it is unusual. It has happened to me for a couple years since using node-red v1. I never actually figure out how to repeat it until recent, then posted in their forum. I may have to rename the subject of that post to have the word BUG in the title to get a response.
