### ISSUE TITLE
Audio only stream [Error: Output stream error: avcC codec info not found]

### ISSUE THREAD

**Issue by nunsie** [kevinGodell/mp4frag#9]
Using an audio only track stream throws the following error:

`Error: Output stream error: avcC codec info not found`

streams with a video track work perfectly.

**Comment by kevinGodell** [comment]
Yes, that is true. At the time when I made it, I had not considered that possibility of an audio only mp4. It will take some time, but I should be able to account for this. Perhaps I should add a user option to add a flag telling the parser that it is audio only or should it be automatic? I will have to investigate the structure of the audio only mp4 to see what makes sense.

**Comment by kevinGodell** [comment]
[commit](https://github.com/kevinGodell/mp4frag/commit/464bbaee74449d0bf947f43e261d43dd73749d4e) adds support for detecting mp4a in an "audio only" mp4
